version: "3.8"

services:
  database:
    image: "bitnami/postgresql:latest"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=police_elixir_dev
    ports:
      - "5432:5432"
